// generated by Fast Light User Interface Designer (fluid) version 1.0300

#include "gui.h"

void Gui::cb_outputDirChooser_i(Fl_Menu_*, void*) {
  app->set_datafile_dir();
}
void Gui::cb_outputDirChooser(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_outputDirChooser_i(o,v);
}

void Gui::cb_readFile_i(Fl_Menu_*, void*) {
  app->readFile();
}
void Gui::cb_readFile(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_readFile_i(o,v);
}

void Gui::cb_readUSBStream_i(Fl_Menu_*, void*) {
  app->readUSBStream();
}
void Gui::cb_readUSBStream(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_readUSBStream_i(o,v);
}

void Gui::cb_readTeleStream_i(Fl_Menu_*, void*) {
  app->readTeleStream();
}
void Gui::cb_readTeleStream(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_readTeleStream_i(o,v);
}

void Gui::cb_WritePicScreen_i(Fl_Menu_*, void*) {
  app->WriteSpec();
}
void Gui::cb_WritePicScreen(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_WritePicScreen_i(o,v);
}

void Gui::cb_WriteLightcurve_i(Fl_Menu_*, void*) {
  app->WriteLightcurve();
}
void Gui::cb_WriteLightcurve(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_WriteLightcurve_i(o,v);
}

void Gui::cb_exitButton_i(Fl_Menu_*, void*) {
  exit(1);
}
void Gui::cb_exitButton(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_exitButton_i(o,v);
}

void Gui::cb_Sync_i(Fl_Menu_*, void*) {
  app->dataSync();
}
void Gui::cb_Sync(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_Sync_i(o,v);
}

void Gui::cb_setDetector0_i(Fl_Menu_*, void*) {
  app->setDetector(0);
}
void Gui::cb_setDetector0(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setDetector0_i(o,v);
}

void Gui::cb_setDetector1_i(Fl_Menu_*, void*) {
  app->setDetector(1);
}
void Gui::cb_setDetector1(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setDetector1_i(o,v);
}

void Gui::cb_setDetector2_i(Fl_Menu_*, void*) {
  app->setDetector(2);
}
void Gui::cb_setDetector2(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setDetector2_i(o,v);
}

void Gui::cb_setDetector3_i(Fl_Menu_*, void*) {
  app->setDetector(3);
}
void Gui::cb_setDetector3(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setDetector3_i(o,v);
}

void Gui::cb_setDetector4_i(Fl_Menu_*, void*) {
  app->setDetector(4);
}
void Gui::cb_setDetector4(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setDetector4_i(o,v);
}

void Gui::cb_setDetector5_i(Fl_Menu_*, void*) {
  app->setDetector(5);
}
void Gui::cb_setDetector5(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setDetector5_i(o,v);
}

void Gui::cb_setDetector6_i(Fl_Menu_*, void*) {
  app->setDetector(6);
}
void Gui::cb_setDetector6(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setDetector6_i(o,v);
}

void Gui::cb_setDetector7_i(Fl_Menu_*, void*) {
  app->setDetector(7);
}
void Gui::cb_setDetector7(Fl_Menu_* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setDetector7_i(o,v);
}

Fl_Menu_Item Gui::menu_menuBar[] = {
 {"File", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Choose Output Dir", 0,  (Fl_Callback*)Gui::cb_outputDirChooser, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Read Data file", 0,  (Fl_Callback*)Gui::cb_readFile, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Read USB Stream", 0,  (Fl_Callback*)Gui::cb_readUSBStream, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Read Tele Stream", 0,  (Fl_Callback*)Gui::cb_readTeleStream, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Write Spec", 0,  (Fl_Callback*)Gui::cb_WritePicScreen, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Write Lightcurve", 0,  (Fl_Callback*)Gui::cb_WriteLightcurve, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Quit", 0x400071,  (Fl_Callback*)Gui::cb_exitButton, 0, 0, FL_NORMAL_LABEL, 0, 14, 1},
 {0,0,0,0,0,0,0,0,0},
 {"Menu", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"Data Sync", 0,  (Fl_Callback*)Gui::cb_Sync, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {"Detector", 0,  0, 0, 64, FL_NORMAL_LABEL, 0, 14, 0},
 {"All", 0,  (Fl_Callback*)Gui::cb_setDetector0, 0, 8, FL_NORMAL_LABEL, 0, 14, 0},
 {"Detector 1", 0,  (Fl_Callback*)Gui::cb_setDetector1, 0, 8, FL_NORMAL_LABEL, 0, 14, 0},
 {"Detector 2", 0,  (Fl_Callback*)Gui::cb_setDetector2, 0, 8, FL_NORMAL_LABEL, 0, 14, 0},
 {"Detector 3", 0,  (Fl_Callback*)Gui::cb_setDetector3, 0, 8, FL_NORMAL_LABEL, 0, 14, 0},
 {"Detector 4", 0,  (Fl_Callback*)Gui::cb_setDetector4, 0, 8, FL_NORMAL_LABEL, 0, 14, 0},
 {"Detector 5", 0,  (Fl_Callback*)Gui::cb_setDetector5, 0, 8, FL_NORMAL_LABEL, 0, 14, 0},
 {"Detector 6", 0,  (Fl_Callback*)Gui::cb_setDetector6, 0, 8, FL_NORMAL_LABEL, 0, 14, 0},
 {"Detector 7", 0,  (Fl_Callback*)Gui::cb_setDetector7, 0, 8, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0},
 {0,0,0,0,0,0,0,0,0}
};
Fl_Menu_Item* Gui::fileMenu = Gui::menu_menuBar + 0;
Fl_Menu_Item* Gui::outputDirChooser = Gui::menu_menuBar + 1;
Fl_Menu_Item* Gui::readFile = Gui::menu_menuBar + 2;
Fl_Menu_Item* Gui::readUSBStream = Gui::menu_menuBar + 3;
Fl_Menu_Item* Gui::readTeleStream = Gui::menu_menuBar + 4;
Fl_Menu_Item* Gui::WritePicScreen = Gui::menu_menuBar + 5;
Fl_Menu_Item* Gui::WriteLightcurve = Gui::menu_menuBar + 6;
Fl_Menu_Item* Gui::exitButton = Gui::menu_menuBar + 7;
Fl_Menu_Item* Gui::menuProc = Gui::menu_menuBar + 9;
Fl_Menu_Item* Gui::Sync = Gui::menu_menuBar + 10;
Fl_Menu_Item* Gui::Detector = Gui::menu_menuBar + 12;
Fl_Menu_Item* Gui::setDetector0 = Gui::menu_menuBar + 13;
Fl_Menu_Item* Gui::setDetector1 = Gui::menu_menuBar + 14;
Fl_Menu_Item* Gui::setDetector2 = Gui::menu_menuBar + 15;
Fl_Menu_Item* Gui::setDetector3 = Gui::menu_menuBar + 16;
Fl_Menu_Item* Gui::setDetector4 = Gui::menu_menuBar + 17;
Fl_Menu_Item* Gui::setDetector5 = Gui::menu_menuBar + 18;
Fl_Menu_Item* Gui::setDetector6 = Gui::menu_menuBar + 19;
Fl_Menu_Item* Gui::setDetector7 = Gui::menu_menuBar + 20;

void Gui::cb_shutterstateOutput_i(Fl_Output*, void*) {
  app->getShutState();
}
void Gui::cb_shutterstateOutput(Fl_Output* o, void* v) {
  ((Gui*)(o->parent()->parent()->user_data()))->cb_shutterstateOutput_i(o,v);
}

void Gui::cb_nextFrameBut_i(Fl_Button*, void*) {
  data->nextFrame();
}
void Gui::cb_nextFrameBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->parent()->user_data()))->cb_nextFrameBut_i(o,v);
}

void Gui::cb_prevFrameBut_i(Fl_Button*, void*) {
  data->previousFrame();
}
void Gui::cb_prevFrameBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->parent()->user_data()))->cb_prevFrameBut_i(o,v);
}

void Gui::cb_flushBut_i(Fl_Button*, void*) {
  app->FlushData();
}
void Gui::cb_flushBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->parent()->user_data()))->cb_flushBut_i(o,v);
}

void Gui::cb_printFrame_i(Fl_Button*, void*) {
  data->printFrame();
}
void Gui::cb_printFrame(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->parent()->user_data()))->cb_printFrame_i(o,v);
}

Fl_Menu_Item Gui::menu_Detector[] = {
 {"All", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Detector 1", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {"Detector 2", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

Fl_Menu_Item Gui::menu_Data[] = {
 {"ACTEL USB", 0,  0, 0, 0, FL_NORMAL_LABEL, 0, 14, 0},
 {0,0,0,0,0,0,0,0,0}
};

void Gui::cb_initializeBut_i(Fl_Light_Button*, void*) {
  app->initialize_data();
}
void Gui::cb_initializeBut(Fl_Light_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_initializeBut_i(o,v);
}

void Gui::cb_startReadingDataButton_i(Fl_Button*, void*) {
  app->start_reading_data();
}
void Gui::cb_startReadingDataButton(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_startReadingDataButton_i(o,v);
}

void Gui::cb_closeBut_i(Fl_Light_Button*, void*) {
  app->close_data();
}
void Gui::cb_closeBut(Fl_Light_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_closeBut_i(o,v);
}

void Gui::cb_sendParamsBut_i(Fl_Button*, void*) {
  app->openSendParamsWindow();
}
void Gui::cb_sendParamsBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_sendParamsBut_i(o,v);
}

void Gui::cb_testBut_i(Fl_Button*, void*) {
  app->test();
}
void Gui::cb_testBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_testBut_i(o,v);
}

void Gui::cb_writeFileBut_i(Fl_Light_Button*, void*) {
  app->start_file();
}
void Gui::cb_writeFileBut(Fl_Light_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_writeFileBut_i(o,v);
}

void Gui::cb_BREAK_i(Fl_Button*, void*) {
  app->break_acq(193);
}
void Gui::cb_BREAK(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_BREAK_i(o,v);
}

void Gui::cb_CLEAR_i(Fl_Button*, void*) {
  app->break_acq(192);
}
void Gui::cb_CLEAR(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_CLEAR_i(o,v);
}

void Gui::cb_setHoldBut_i(Fl_Button*, void*) {
  app->openSetHoldTimeWindow();
}
void Gui::cb_setHoldBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setHoldBut_i(o,v);
}

void Gui::cb_Clear_i(Fl_Button*, void*) {
  app->clear_console();
}
void Gui::cb_Clear(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_Clear_i(o,v);
}

void Gui::cb_setTrigBut_i(Fl_Button*, void*) {
  app->openSetTrigWindow();
}
void Gui::cb_setTrigBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setTrigBut_i(o,v);
}

void Gui::cb_stopReadingDataButton_i(Fl_Light_Button*, void*) {
  app->stop_reading_data();
}
void Gui::cb_stopReadingDataButton(Fl_Light_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_stopReadingDataButton_i(o,v);
}

void Gui::cb_sendParamsWindow_sendBut_i(Fl_Button*, void*) {
  app->save_settings();
app->send_params();
//sendParamsWindow->hide();
}
void Gui::cb_sendParamsWindow_sendBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_sendParamsWindow_sendBut_i(o,v);
}

void Gui::cb_Close_i(Fl_Button*, void*) {
  sendParamsWindow->hide();
}
void Gui::cb_Close(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_Close_i(o,v);
}

void Gui::cb_sendParamsWindow_asic_i(Fl_Value_Input*, void*) {
  app->restore_settings();
}
void Gui::cb_sendParamsWindow_asic(Fl_Value_Input* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_sendParamsWindow_asic_i(o,v);
}

void Gui::cb_set_i(Fl_Button*, void*) {
  for(int i=0; i<64; i++) 
  sendParamsWindow_chan[i]->set();
}
void Gui::cb_set(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_set_i(o,v);
}

void Gui::cb_clear_i(Fl_Button*, void*) {
  for(int i=0; i<64; i++) 
  sendParamsWindow_chan[i]->clear();
}
void Gui::cb_clear(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_clear_i(o,v);
}

void Gui::cb_set1_i(Fl_Button*, void*) {
  for(int i=0; i<64; i++) 
  sendParamsWindow_test[i]->set();
}
void Gui::cb_set1(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_set1_i(o,v);
}

void Gui::cb_clear1_i(Fl_Button*, void*) {
  for(int i=0; i<64; i++) 
  sendParamsWindow_test[i]->clear();
}
void Gui::cb_clear1(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_clear1_i(o,v);
}

void Gui::cb_setHoldTimeWindow_setBut_i(Fl_Button*, void*) {
  app->send_global_params(0);
}
void Gui::cb_setHoldTimeWindow_setBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setHoldTimeWindow_setBut_i(o,v);
}

void Gui::cb_setHoldTimeWindow_autorunBut_i(Fl_Button*, void*) {
  app->start_auto_run();
}
void Gui::cb_setHoldTimeWindow_autorunBut(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setHoldTimeWindow_autorunBut_i(o,v);
}

void Gui::cb_Close1_i(Fl_Button*, void*) {
  setHoldTimeWindow->hide();
}
void Gui::cb_Close1(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_Close1_i(o,v);
}

void Gui::cb_Close2_i(Fl_Button*, void*) {
  setTrigWindow->hide();
}
void Gui::cb_Close2(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_Close2_i(o,v);
}

void Gui::cb_setTrigWindow_setDelay_i(Fl_Button*, void*) {
  app->send_global_params(3);
}
void Gui::cb_setTrigWindow_setDelay(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setTrigWindow_setDelay_i(o,v);
}

void Gui::cb_setTrigWindow_setTimeout_i(Fl_Button*, void*) {
  app->send_global_params(1);
}
void Gui::cb_setTrigWindow_setTimeout(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setTrigWindow_setTimeout_i(o,v);
}

void Gui::cb_setTrigWindow_useTimeout_i(Fl_Value_Input*, void*) {
  if(setTrigWindow_useTimeout->value()){
setTrigWindow_setTimeout->activate();
setTrigWindow_timeoutTime->activate();
} else{
setTrigWindow_setTimeout->deactivate();
setTrigWindow_timeoutTime->deactivate();
};
}
void Gui::cb_setTrigWindow_useTimeout(Fl_Value_Input* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setTrigWindow_useTimeout_i(o,v);
}

void Gui::cb_setTrigWindow_setTrigMode_i(Fl_Button*, void*) {
  app->send_global_params(2);
}
void Gui::cb_setTrigWindow_setTrigMode(Fl_Button* o, void* v) {
  ((Gui*)(o->parent()->user_data()))->cb_setTrigWindow_setTrigMode_i(o,v);
}

Gui::Gui() {
  { mainWindow = new Fl_Double_Window(1252, 683, "FOXSI GSE");
    mainWindow->color((Fl_Color)19);
    mainWindow->user_data((void*)(this));
    { menuBar = new Fl_Menu_Bar(-5, -1, 1255, 25, "menuBar");
      menuBar->box(FL_BORDER_BOX);
      menuBar->color((Fl_Color)29);
      menuBar->menu(menu_menuBar);
    } // Fl_Menu_Bar* menuBar
    { mainHistogramWindow = new mainHistogram(625, 460, 265, 240, "Histogram");
      mainHistogramWindow->box(FL_GTK_UP_BOX);
      mainHistogramWindow->color(FL_BACKGROUND_COLOR);
      mainHistogramWindow->selection_color(FL_BACKGROUND_COLOR);
      mainHistogramWindow->labeltype(FL_NORMAL_LABEL);
      mainHistogramWindow->labelfont(0);
      mainHistogramWindow->labelsize(14);
      mainHistogramWindow->labelcolor(FL_FOREGROUND_COLOR);
      mainHistogramWindow->align(Fl_Align(FL_ALIGN_CENTER));
      mainHistogramWindow->when(FL_WHEN_RELEASE);
    } // mainHistogram* mainHistogramWindow
    { mainImageWindow = new mainImage(3, 313, 402, 397, "Image");
      mainImageWindow->box(FL_GTK_UP_BOX);
      mainImageWindow->color(FL_BACKGROUND_COLOR);
      mainImageWindow->selection_color(FL_BACKGROUND_COLOR);
      mainImageWindow->labeltype(FL_NORMAL_LABEL);
      mainImageWindow->labelfont(0);
      mainImageWindow->labelsize(14);
      mainImageWindow->labelcolor(FL_FOREGROUND_COLOR);
      mainImageWindow->align(Fl_Align(FL_ALIGN_CENTER));
      mainImageWindow->when(FL_WHEN_RELEASE);
    } // mainImage* mainImageWindow
    { subImageWindow = new subImage(415, 315, 145, 140, "Image Zoom");
      subImageWindow->box(FL_GTK_UP_BOX);
      subImageWindow->color(FL_BACKGROUND_COLOR);
      subImageWindow->selection_color(FL_BACKGROUND_COLOR);
      subImageWindow->labeltype(FL_NORMAL_LABEL);
      subImageWindow->labelfont(0);
      subImageWindow->labelsize(14);
      subImageWindow->labelcolor(FL_FOREGROUND_COLOR);
      subImageWindow->align(Fl_Align(FL_ALIGN_CENTER));
      subImageWindow->when(FL_WHEN_RELEASE);
    } // subImage* subImageWindow
    { TopOutput = new Fl_Group(325, 35, 695, 520);
      { rateOutput0 = new Fl_Output(375, 115, 80, 25, "Rate [cts/s]");
      } // Fl_Output* rateOutput0
      { rateOutput1 = new Fl_Output(460, 115, 45, 25);
      } // Fl_Output* rateOutput1
      { rateOutput2 = new Fl_Output(510, 115, 45, 25);
      } // Fl_Output* rateOutput2
      { rateOutput3 = new Fl_Output(560, 115, 45, 25);
      } // Fl_Output* rateOutput3
      { rateOutput4 = new Fl_Output(610, 115, 45, 25);
      } // Fl_Output* rateOutput4
      { rateOutput5 = new Fl_Output(660, 115, 45, 25);
      } // Fl_Output* rateOutput5
      { rateOutput6 = new Fl_Output(710, 115, 45, 25);
      } // Fl_Output* rateOutput6
      { rateOutput7 = new Fl_Output(760, 115, 45, 25);
      } // Fl_Output* rateOutput7
      { framenumOutput = new Fl_Output(605, 35, 45, 25, "Frame #");
      } // Fl_Output* framenumOutput
      { shutterstateOutput = new Fl_Output(465, 65, 30, 25, "Shut state");
        shutterstateOutput->callback((Fl_Callback*)cb_shutterstateOutput);
      } // Fl_Output* shutterstateOutput
      { TempOutput = new Fl_Output(375, 145, 30, 25, "Temp");
      } // Fl_Output* TempOutput
      { histEnergy = new Fl_Output(940, 500, 80, 25, "Energy");
      } // Fl_Output* histEnergy
      { histCounts = new Fl_Output(940, 530, 80, 25, "Counts");
      } // Fl_Output* histCounts
      TopOutput->end();
    } // Fl_Group* TopOutput
    { dataPlayback = new Fl_Group(560, 35, 599, 106);
      { nextFrameBut = new Fl_Button(675, 65, 80, 25, "Next Frame");
        nextFrameBut->callback((Fl_Callback*)cb_nextFrameBut);
      } // Fl_Button* nextFrameBut
      { prevFrameBut = new Fl_Button(560, 65, 110, 25, "Previous Frame");
        prevFrameBut->callback((Fl_Callback*)cb_prevFrameBut);
      } // Fl_Button* prevFrameBut
      { syncLightBut = new Fl_Light_Button(765, 35, 70, 25, "Sync");
      } // Fl_Light_Button* syncLightBut
      { flushBut = new Fl_Button(840, 35, 80, 25, "Flush");
        flushBut->callback((Fl_Callback*)cb_flushBut);
      } // Fl_Button* flushBut
      { printFrame = new Fl_Button(760, 65, 80, 25, "Print Frame");
        printFrame->callback((Fl_Callback*)cb_printFrame);
      } // Fl_Button* printFrame
      { frameTime = new Fl_Value_Output(725, 36, 33, 24, "frame time");
      } // Fl_Value_Output* frameTime
      { Fl_Group* o = new Fl_Group(1010, 36, 148, 24);
        { chipbitValOut0 = new Fl_Value_Output(1010, 36, 33, 24, "Chip bit");
          chipbitValOut0->deactivate();
        } // Fl_Value_Output* chipbitValOut0
        { chipbitValOut1 = new Fl_Value_Output(1046, 36, 33, 24);
          chipbitValOut1->deactivate();
        } // Fl_Value_Output* chipbitValOut1
        { chipbitValOut2 = new Fl_Value_Output(1085, 36, 33, 24);
          chipbitValOut2->deactivate();
        } // Fl_Value_Output* chipbitValOut2
        { chipbitValOut3 = new Fl_Value_Output(1125, 36, 33, 24);
          chipbitValOut3->deactivate();
        } // Fl_Value_Output* chipbitValOut3
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(1010, 63, 148, 24);
        { trigbitValOut0 = new Fl_Value_Output(1010, 63, 33, 24, "Trig bit");
          trigbitValOut0->deactivate();
        } // Fl_Value_Output* trigbitValOut0
        { trigbitValOut1 = new Fl_Value_Output(1046, 63, 33, 24);
          trigbitValOut1->deactivate();
        } // Fl_Value_Output* trigbitValOut1
        { trigbitValOut2 = new Fl_Value_Output(1085, 63, 33, 24);
          trigbitValOut2->deactivate();
        } // Fl_Value_Output* trigbitValOut2
        { trigbitValOut3 = new Fl_Value_Output(1125, 63, 33, 24);
          trigbitValOut3->deactivate();
        } // Fl_Value_Output* trigbitValOut3
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(1010, 90, 148, 24);
        { seubitValOut0 = new Fl_Value_Output(1010, 90, 33, 24, "SEU bit");
          seubitValOut0->deactivate();
        } // Fl_Value_Output* seubitValOut0
        { seubitValOut1 = new Fl_Value_Output(1046, 90, 33, 24);
          seubitValOut1->deactivate();
        } // Fl_Value_Output* seubitValOut1
        { seubitValOut2 = new Fl_Value_Output(1085, 90, 33, 24);
          seubitValOut2->deactivate();
        } // Fl_Value_Output* seubitValOut2
        { seubitValOut3 = new Fl_Value_Output(1125, 90, 33, 24);
          seubitValOut3->deactivate();
        } // Fl_Value_Output* seubitValOut3
        o->end();
      } // Fl_Group* o
      { Fl_Group* o = new Fl_Group(1011, 117, 148, 24);
        { noiseValOut0 = new Fl_Value_Output(1011, 117, 33, 24, "Noise");
          noiseValOut0->deactivate();
        } // Fl_Value_Output* noiseValOut0
        { noiseValOut1 = new Fl_Value_Output(1047, 117, 33, 24);
          noiseValOut1->deactivate();
        } // Fl_Value_Output* noiseValOut1
        { noiseValOut2 = new Fl_Value_Output(1086, 117, 33, 24);
          noiseValOut2->deactivate();
        } // Fl_Value_Output* noiseValOut2
        { noiseValOut3 = new Fl_Value_Output(1126, 117, 33, 24);
          noiseValOut3->deactivate();
        } // Fl_Value_Output* noiseValOut3
        o->end();
      } // Fl_Group* o
      dataPlayback->end();
    } // Fl_Group* dataPlayback
    { mainChartWindow = new mainChart(470, 155, 130, 115, "1");
      mainChartWindow->box(FL_GTK_UP_BOX);
      mainChartWindow->color(FL_BACKGROUND_COLOR);
      mainChartWindow->selection_color(FL_BACKGROUND_COLOR);
      mainChartWindow->labeltype(FL_NO_LABEL);
      mainChartWindow->labelfont(0);
      mainChartWindow->labelsize(14);
      mainChartWindow->labelcolor(FL_FOREGROUND_COLOR);
      mainChartWindow->align(Fl_Align(FL_ALIGN_CENTER));
      mainChartWindow->when(FL_WHEN_RELEASE);
    } // mainChart* mainChartWindow
    { pixelNum = new Fl_Output(445, 495, 80, 25, "Pixel");
    } // Fl_Output* pixelNum
    { pixelCounts = new Fl_Output(445, 465, 80, 25, "Cts");
    } // Fl_Output* pixelCounts
    { subImageLockbut = new Fl_Light_Button(420, 525, 105, 25, "Unlock View");
      subImageLockbut->selection_color((Fl_Color)1);
    } // Fl_Light_Button* subImageLockbut
    { new Fl_Text_Display(529, 295, 15, 15, "detector 1");
    } // Fl_Text_Display* o
    { mainHistogramLockbut = new Fl_Light_Button(900, 465, 65, 25, "Unlock");
      mainHistogramLockbut->selection_color((Fl_Color)1);
    } // Fl_Light_Button* mainHistogramLockbut
    { mainChartWindow1 = new mainChart(615, 155, 130, 115, "1");
      mainChartWindow1->box(FL_GTK_UP_BOX);
      mainChartWindow1->color(FL_BACKGROUND_COLOR);
      mainChartWindow1->selection_color(FL_BACKGROUND_COLOR);
      mainChartWindow1->labeltype(FL_NO_LABEL);
      mainChartWindow1->labelfont(0);
      mainChartWindow1->labelsize(14);
      mainChartWindow1->labelcolor(FL_FOREGROUND_COLOR);
      mainChartWindow1->align(Fl_Align(FL_ALIGN_CENTER));
      mainChartWindow1->when(FL_WHEN_RELEASE);
    } // mainChart* mainChartWindow1
    { new Fl_Text_Display(670, 295, 15, 15, "detector 2");
    } // Fl_Text_Display* o
    { mainHistogramXlabelmid = new Fl_Value_Output(735, 707, 35, 23, "Energy:");
      mainHistogramXlabelmid->box(FL_THIN_UP_BOX);
    } // Fl_Value_Output* mainHistogramXlabelmid
    { mainHistogramXlabelmax = new Fl_Value_Output(865, 707, 35, 23);
      mainHistogramXlabelmax->box(FL_THIN_UP_BOX);
    } // Fl_Value_Output* mainHistogramXlabelmax
    { mainHistogramYlabelmax = new Fl_Value_Output(585, 457, 35, 23);
      mainHistogramYlabelmax->box(FL_THIN_UP_BOX);
    } // Fl_Value_Output* mainHistogramYlabelmax
    { mainHistogramYlabelmid = new Fl_Value_Output(585, 577, 35, 23);
      mainHistogramYlabelmid->box(FL_THIN_UP_BOX);
    } // Fl_Value_Output* mainHistogramYlabelmid
    { consoleBuf = new Fl_Text_Display(590, 320, 520, 130);
    } // Fl_Text_Display* consoleBuf
    { Fl_Choice* o = new Fl_Choice(90, 65, 95, 25, "Detector:");
      o->down_box(FL_BORDER_BOX);
      o->menu(menu_Detector);
    } // Fl_Choice* o
    { Fl_Choice* o = new Fl_Choice(90, 35, 115, 25, "Data Source:");
      o->down_box(FL_BORDER_BOX);
      o->menu(menu_Data);
    } // Fl_Choice* o
    { initializeBut = new Fl_Light_Button(209, 35, 80, 25, "Initialize");
      initializeBut->box(FL_THIN_UP_BOX);
      initializeBut->callback((Fl_Callback*)cb_initializeBut);
    } // Fl_Light_Button* initializeBut
    { startReadingDataButton = new Fl_Button(390, 35, 60, 25, "Read");
      startReadingDataButton->callback((Fl_Callback*)cb_startReadingDataButton);
      startReadingDataButton->deactivate();
    } // Fl_Button* startReadingDataButton
    { closeBut = new Fl_Light_Button(209, 65, 80, 25, "Close");
      closeBut->callback((Fl_Callback*)cb_closeBut);
    } // Fl_Light_Button* closeBut
    { mainLightcurveWindow = new mainLightcurve(760, 155, 300, 125, "Light curve");
      mainLightcurveWindow->box(FL_GTK_UP_BOX);
      mainLightcurveWindow->color(FL_BACKGROUND_COLOR);
      mainLightcurveWindow->selection_color(FL_BACKGROUND_COLOR);
      mainLightcurveWindow->labeltype(FL_NORMAL_LABEL);
      mainLightcurveWindow->labelfont(0);
      mainLightcurveWindow->labelsize(14);
      mainLightcurveWindow->labelcolor(FL_FOREGROUND_COLOR);
      mainLightcurveWindow->align(Fl_Align(FL_ALIGN_CENTER));
      mainLightcurveWindow->when(FL_WHEN_RELEASE);
    } // mainLightcurve* mainLightcurveWindow
    { glitchBut = new Fl_Light_Button(90, 100, 75, 25, "Glitch");
    } // Fl_Light_Button* glitchBut
    { sendParamsBut = new Fl_Button(83, 140, 100, 25, "Send Params");
      sendParamsBut->callback((Fl_Callback*)cb_sendParamsBut);
    } // Fl_Button* sendParamsBut
    { testBut = new Fl_Button(15, 275, 75, 25, "Test");
      testBut->callback((Fl_Callback*)cb_testBut);
    } // Fl_Button* testBut
    { nEvents = new Fl_Value_Input(345, 35, 40, 24, "events");
      nEvents->value(1);
    } // Fl_Value_Input* nEvents
    { writeFileBut = new Fl_Light_Button(85, 210, 95, 25, "Write to file");
      writeFileBut->callback((Fl_Callback*)cb_writeFileBut);
    } // Fl_Light_Button* writeFileBut
    { nEventsDone = new Fl_Value_Input(345, 66, 40, 24, "counter");
      nEventsDone->value(1);
    } // Fl_Value_Input* nEventsDone
    { Fl_Button* o = new Fl_Button(215, 245, 63, 20, "BREAK");
      o->callback((Fl_Callback*)cb_BREAK);
      o->deactivate();
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(215, 270, 63, 20, "CLEAR");
      o->callback((Fl_Callback*)cb_CLEAR);
      o->deactivate();
    } // Fl_Button* o
    { setHoldBut = new Fl_Button(85, 175, 100, 25, "Set Hold Time");
      setHoldBut->callback((Fl_Callback*)cb_setHoldBut);
    } // Fl_Button* setHoldBut
    { Fl_Button* o = new Fl_Button(1115, 320, 63, 20, "Clear");
      o->labelcolor((Fl_Color)1);
      o->callback((Fl_Callback*)cb_Clear);
    } // Fl_Button* o
    { setTrigBut = new Fl_Button(198, 175, 125, 25, "Set Trigger Options");
      setTrigBut->callback((Fl_Callback*)cb_setTrigBut);
    } // Fl_Button* setTrigBut
    { stopReadingDataButton = new Fl_Light_Button(455, 35, 75, 25, "Stop");
      stopReadingDataButton->labelcolor((Fl_Color)1);
      stopReadingDataButton->callback((Fl_Callback*)cb_stopReadingDataButton);
      stopReadingDataButton->deactivate();
    } // Fl_Light_Button* stopReadingDataButton
    mainWindow->end();
    mainWindow->resizable(mainWindow);
  } // Fl_Double_Window* mainWindow
  app=new Application();
  data=new Foxsidata();
  usb=new USB_d2xx();
  buff=new Fl_Text_Buffer();
  consoleBuf->buffer(buff);
  { sendParamsWindow = new Fl_Double_Window(1053, 524, "Send Parameters");
    sendParamsWindow->user_data((void*)(this));
    { sendParamsWindow_sendBut = new Fl_Button(415, 425, 70, 25, "Send");
      sendParamsWindow_sendBut->value(1);
      sendParamsWindow_sendBut->callback((Fl_Callback*)cb_sendParamsWindow_sendBut);
    } // Fl_Button* sendParamsWindow_sendBut
    { sendParamsWindow_value[0] = new Fl_Value_Input(135, 11, 40, 24, "Vfss_neg:");
      sendParamsWindow_value[0]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[0]
    { sendParamsWindow_value[1] = new Fl_Value_Input(135, 38, 40, 24, "Tp_longb:");
      sendParamsWindow_value[1]->maximum(7);
      sendParamsWindow_value[1]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[1]
    { Fl_Button* o = new Fl_Button(415, 460, 70, 25, "Close");
      o->callback((Fl_Callback*)cb_Close);
    } // Fl_Button* o
    { sendParamsWindow_value[2] = new Fl_Value_Input(135, 65, 40, 23, "Sbi_hp1:");
      sendParamsWindow_value[2]->maximum(7);
      sendParamsWindow_value[2]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[2]
    { sendParamsWindow_value[3] = new Fl_Value_Input(135, 92, 40, 23, "Sbi_hp2b:");
      sendParamsWindow_value[3]->maximum(7);
      sendParamsWindow_value[3]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[3]
    { sendParamsWindow_value[4] = new Fl_Value_Input(135, 118, 40, 24, "Iramp_fb:");
      sendParamsWindow_value[4]->maximum(7);
      sendParamsWindow_value[4]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[4]
    { sendParamsWindow_value[5] = new Fl_Value_Input(135, 146, 40, 24, "Iramp_f2:");
      sendParamsWindow_value[5]->maximum(7);
      sendParamsWindow_value[5]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[5]
    { sendParamsWindow_value[6] = new Fl_Value_Input(135, 173, 40, 24, "CM_thr_dis:");
      sendParamsWindow_value[6]->maximum(7);
      sendParamsWindow_value[6]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[6]
    { sendParamsWindow_value[7] = new Fl_Value_Input(135, 201, 40, 24, "RO_all:");
      sendParamsWindow_value[7]->maximum(7);
      sendParamsWindow_value[7]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[7]
    { sendParamsWindow_value[8] = new Fl_Value_Input(135, 228, 40, 24, "Ck_en:");
      sendParamsWindow_value[8]->maximum(7);
      sendParamsWindow_value[8]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[8]
    { sendParamsWindow_value[9] = new Fl_Value_Input(135, 256, 40, 24, "Prebi_hp:");
      sendParamsWindow_value[9]->maximum(7);
      sendParamsWindow_value[9]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[9]
    { sendParamsWindow_value[10] = new Fl_Value_Input(135, 284, 40, 24, "Cal_gen_on:");
      sendParamsWindow_value[10]->maximum(7);
      sendParamsWindow_value[10]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[10]
    { sendParamsWindow_value[11] = new Fl_Value_Input(135, 311, 40, 24, "Slew_on_b:");
      sendParamsWindow_value[11]->maximum(7);
      sendParamsWindow_value[11]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[11]
    { sendParamsWindow_value[12] = new Fl_Value_Input(135, 338, 40, 24, "Nside:");
      sendParamsWindow_value[12]->maximum(7);
      sendParamsWindow_value[12]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[12]
    { sendParamsWindow_value[13] = new Fl_Value_Input(135, 365, 40, 24, "CC_on:");
      sendParamsWindow_value[13]->maximum(7);
      sendParamsWindow_value[13]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[13]
    { sendParamsWindow_value[14] = new Fl_Value_Input(135, 392, 40, 24, "Test_on:");
      sendParamsWindow_value[14]->maximum(7);
      sendParamsWindow_value[14]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[14]
    { sendParamsWindow_value[15] = new Fl_Value_Input(135, 420, 40, 24, "Low_gain:");
      sendParamsWindow_value[15]->maximum(7);
      sendParamsWindow_value[15]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[15]
    { sendParamsWindow_value[16] = new Fl_Value_Input(290, 13, 40, 24, "negQ:");
      sendParamsWindow_value[16]->maximum(7);
      sendParamsWindow_value[16]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[16]
    { sendParamsWindow_value[17] = new Fl_Value_Input(290, 40, 40, 24, "Reserved");
      sendParamsWindow_value[17]->maximum(7);
      sendParamsWindow_value[17]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[17]
    { sendParamsWindow_value[18] = new Fl_Value_Input(290, 67, 40, 24, "ADC_on_b:");
      sendParamsWindow_value[18]->maximum(7);
      sendParamsWindow_value[18]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[18]
    { sendParamsWindow_value[19] = new Fl_Value_Input(290, 95, 40, 24, "VA_RO:");
      sendParamsWindow_value[19]->maximum(7);
      sendParamsWindow_value[19]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[19]
    { sendParamsWindow_value[20] = new Fl_Value_Input(290, 120, 40, 24, "Vrc_negQ:");
      sendParamsWindow_value[20]->maximum(7);
      sendParamsWindow_value[20]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[20]
    { sendParamsWindow_value[21] = new Fl_Value_Input(290, 147, 40, 24, "Ileak_offset:");
      sendParamsWindow_value[21]->maximum(7);
      sendParamsWindow_value[21]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[21]
    { sendParamsWindow_value[22] = new Fl_Value_Input(290, 174, 40, 24, "ADC_test1:");
      sendParamsWindow_value[22]->maximum(7);
      sendParamsWindow_value[22]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[22]
    { sendParamsWindow_value[23] = new Fl_Value_Input(290, 201, 40, 24, "ADC_test2:");
      sendParamsWindow_value[23]->maximum(7);
      sendParamsWindow_value[23]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[23]
    { sendParamsWindow_value[24] = new Fl_Value_Input(290, 229, 40, 24, "Delay, dummy:");
      sendParamsWindow_value[24]->maximum(63);
      sendParamsWindow_value[24]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[24]
    { sendParamsWindow_value[25] = new Fl_Value_Input(290, 257, 40, 24, "Digital threshold:");
      sendParamsWindow_value[25]->maximum(255);
      sendParamsWindow_value[25]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[25]
    { sendParamsWindow_value[26] = new Fl_Value_Input(290, 284, 40, 24, "Shabi_lg:");
      sendParamsWindow_value[26]->maximum(7);
      sendParamsWindow_value[26]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[26]
    { sendParamsWindow_value[27] = new Fl_Value_Input(290, 311, 40, 24, "Pos_Il_1:");
      sendParamsWindow_value[27]->maximum(7);
      sendParamsWindow_value[27]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[27]
    { sendParamsWindow_value[28] = new Fl_Value_Input(290, 338, 40, 24, "Pos_Il_2:");
      sendParamsWindow_value[28]->maximum(7);
      sendParamsWindow_value[28]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[28]
    { sendParamsWindow_value[29] = new Fl_Value_Input(290, 366, 40, 24, "Bias DAC, vthr:");
      sendParamsWindow_value[29]->maximum(31);
      sendParamsWindow_value[29]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[29]
    { sendParamsWindow_value[30] = new Fl_Value_Input(290, 394, 40, 24, "Bias DAC, ifp:");
      sendParamsWindow_value[30]->maximum(31);
      sendParamsWindow_value[30]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[30]
    { sendParamsWindow_value[31] = new Fl_Value_Input(290, 421, 40, 24, "Bias DAC, Iramp:");
      sendParamsWindow_value[31]->maximum(31);
      sendParamsWindow_value[31]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[31]
    { sendParamsWindow_value[32] = new Fl_Value_Input(480, 14, 40, 24, "Bias DAC, ck_bi:");
      sendParamsWindow_value[32]->maximum(31);
      sendParamsWindow_value[32]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[32]
    { sendParamsWindow_value[33] = new Fl_Value_Input(480, 41, 40, 24, "Bias DAC, cal_bi:");
      sendParamsWindow_value[33]->maximum(31);
      sendParamsWindow_value[33]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[33]
    { sendParamsWindow_value[34] = new Fl_Value_Input(480, 68, 40, 24, "Bias DAC, twbi:");
      sendParamsWindow_value[34]->maximum(31);
      sendParamsWindow_value[34]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[34]
    { sendParamsWindow_value[35] = new Fl_Value_Input(480, 96, 40, 24, "Bias DAC, sha_bias:");
      sendParamsWindow_value[35]->maximum(31);
      sendParamsWindow_value[35]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[35]
    { sendParamsWindow_value[36] = new Fl_Value_Input(480, 123, 40, 24, "Bias DAC, ifss:");
      sendParamsWindow_value[36]->maximum(31);
      sendParamsWindow_value[36]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[36]
    { sendParamsWindow_value[37] = new Fl_Value_Input(480, 150, 40, 24, "Bias DAC, ifsf:");
      sendParamsWindow_value[37]->maximum(31);
      sendParamsWindow_value[37]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[37]
    { sendParamsWindow_value[38] = new Fl_Value_Input(480, 177, 40, 24, "Bias DAC, vrc:");
      sendParamsWindow_value[38]->maximum(31);
      sendParamsWindow_value[38]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[38]
    { sendParamsWindow_value[39] = new Fl_Value_Input(480, 205, 40, 24, "Bias DAC, sbi:");
      sendParamsWindow_value[39]->maximum(31);
      sendParamsWindow_value[39]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[39]
    { sendParamsWindow_value[40] = new Fl_Value_Input(480, 232, 40, 24, "Bias DAC, pre_bias:");
      sendParamsWindow_value[40]->maximum(31);
      sendParamsWindow_value[40]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[40]
    { sendParamsWindow_value[41] = new Fl_Value_Input(480, 260, 40, 24, "Bias DAC, ibuf:");
      sendParamsWindow_value[41]->maximum(31);
      sendParamsWindow_value[41]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[41]
    { sendParamsWindow_value[42] = new Fl_Value_Input(480, 287, 40, 24, "Bias DAC, obi:");
      sendParamsWindow_value[42]->maximum(31);
      sendParamsWindow_value[42]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[42]
    { sendParamsWindow_value[43] = new Fl_Value_Input(480, 314, 40, 24, "Bias DAC, Ioffset:");
      sendParamsWindow_value[43]->maximum(31);
      sendParamsWindow_value[43]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[43]
    { sendParamsWindow_value[44] = new Fl_Value_Input(480, 341, 40, 24, "Bias DAC, disc3_bi:");
      sendParamsWindow_value[44]->maximum(31);
      sendParamsWindow_value[44]->step(1);
    } // Fl_Value_Input* sendParamsWindow_value[44]
    { sendParamsWindow_chan[0] = new Fl_Light_Button(555, 35, 67, 20, "0");
    } // Fl_Light_Button* sendParamsWindow_chan[0]
    { sendParamsWindow_chan[1] = new Fl_Light_Button(555, 55, 67, 20, "1");
    } // Fl_Light_Button* sendParamsWindow_chan[1]
    { sendParamsWindow_chan[2] = new Fl_Light_Button(555, 75, 67, 20, "2");
    } // Fl_Light_Button* sendParamsWindow_chan[2]
    { sendParamsWindow_chan[3] = new Fl_Light_Button(555, 95, 67, 20, "3");
    } // Fl_Light_Button* sendParamsWindow_chan[3]
    { sendParamsWindow_chan[4] = new Fl_Light_Button(555, 115, 67, 20, "4");
    } // Fl_Light_Button* sendParamsWindow_chan[4]
    { sendParamsWindow_chan[5] = new Fl_Light_Button(555, 135, 67, 20, "5");
    } // Fl_Light_Button* sendParamsWindow_chan[5]
    { sendParamsWindow_chan[6] = new Fl_Light_Button(555, 155, 67, 20, "6");
    } // Fl_Light_Button* sendParamsWindow_chan[6]
    { sendParamsWindow_chan[7] = new Fl_Light_Button(555, 175, 67, 20, "7");
    } // Fl_Light_Button* sendParamsWindow_chan[7]
    { sendParamsWindow_chan[8] = new Fl_Light_Button(555, 195, 67, 20, "8");
    } // Fl_Light_Button* sendParamsWindow_chan[8]
    { sendParamsWindow_chan[9] = new Fl_Light_Button(555, 215, 67, 20, "9");
    } // Fl_Light_Button* sendParamsWindow_chan[9]
    { sendParamsWindow_chan[10] = new Fl_Light_Button(555, 235, 67, 20, "10");
    } // Fl_Light_Button* sendParamsWindow_chan[10]
    { sendParamsWindow_chan[11] = new Fl_Light_Button(555, 255, 67, 20, "11");
    } // Fl_Light_Button* sendParamsWindow_chan[11]
    { sendParamsWindow_chan[12] = new Fl_Light_Button(555, 275, 67, 20, "12");
    } // Fl_Light_Button* sendParamsWindow_chan[12]
    { sendParamsWindow_chan[13] = new Fl_Light_Button(555, 295, 67, 20, "13");
    } // Fl_Light_Button* sendParamsWindow_chan[13]
    { sendParamsWindow_chan[14] = new Fl_Light_Button(555, 315, 67, 20, "14");
    } // Fl_Light_Button* sendParamsWindow_chan[14]
    { sendParamsWindow_chan[15] = new Fl_Light_Button(555, 335, 67, 20, "15");
    } // Fl_Light_Button* sendParamsWindow_chan[15]
    { sendParamsWindow_chan[16] = new Fl_Light_Button(555, 355, 67, 20, "16");
    } // Fl_Light_Button* sendParamsWindow_chan[16]
    { sendParamsWindow_chan[17] = new Fl_Light_Button(555, 375, 67, 20, "17");
    } // Fl_Light_Button* sendParamsWindow_chan[17]
    { sendParamsWindow_chan[18] = new Fl_Light_Button(555, 395, 67, 20, "18");
    } // Fl_Light_Button* sendParamsWindow_chan[18]
    { sendParamsWindow_chan[19] = new Fl_Light_Button(555, 415, 67, 20, "19");
    } // Fl_Light_Button* sendParamsWindow_chan[19]
    { sendParamsWindow_chan[20] = new Fl_Light_Button(555, 435, 67, 20, "20");
    } // Fl_Light_Button* sendParamsWindow_chan[20]
    { sendParamsWindow_chan[21] = new Fl_Light_Button(620, 35, 67, 20, "21");
    } // Fl_Light_Button* sendParamsWindow_chan[21]
    { sendParamsWindow_chan[22] = new Fl_Light_Button(620, 55, 67, 20, "22");
    } // Fl_Light_Button* sendParamsWindow_chan[22]
    { sendParamsWindow_chan[23] = new Fl_Light_Button(620, 75, 67, 20, "23");
    } // Fl_Light_Button* sendParamsWindow_chan[23]
    { sendParamsWindow_chan[24] = new Fl_Light_Button(620, 95, 67, 20, "24");
    } // Fl_Light_Button* sendParamsWindow_chan[24]
    { sendParamsWindow_chan[25] = new Fl_Light_Button(620, 115, 67, 20, "25");
    } // Fl_Light_Button* sendParamsWindow_chan[25]
    { sendParamsWindow_chan[26] = new Fl_Light_Button(620, 135, 67, 20, "26");
    } // Fl_Light_Button* sendParamsWindow_chan[26]
    { sendParamsWindow_chan[27] = new Fl_Light_Button(620, 155, 67, 20, "27");
    } // Fl_Light_Button* sendParamsWindow_chan[27]
    { sendParamsWindow_chan[28] = new Fl_Light_Button(620, 175, 67, 20, "28");
    } // Fl_Light_Button* sendParamsWindow_chan[28]
    { sendParamsWindow_chan[29] = new Fl_Light_Button(620, 195, 67, 20, "29");
    } // Fl_Light_Button* sendParamsWindow_chan[29]
    { sendParamsWindow_chan[30] = new Fl_Light_Button(620, 215, 67, 20, "30");
    } // Fl_Light_Button* sendParamsWindow_chan[30]
    { sendParamsWindow_chan[31] = new Fl_Light_Button(620, 235, 67, 20, "31");
    } // Fl_Light_Button* sendParamsWindow_chan[31]
    { sendParamsWindow_chan[32] = new Fl_Light_Button(620, 255, 67, 20, "32");
    } // Fl_Light_Button* sendParamsWindow_chan[32]
    { sendParamsWindow_chan[33] = new Fl_Light_Button(620, 275, 67, 20, "33");
    } // Fl_Light_Button* sendParamsWindow_chan[33]
    { sendParamsWindow_chan[34] = new Fl_Light_Button(620, 295, 67, 20, "34");
    } // Fl_Light_Button* sendParamsWindow_chan[34]
    { sendParamsWindow_chan[35] = new Fl_Light_Button(620, 315, 67, 20, "35");
    } // Fl_Light_Button* sendParamsWindow_chan[35]
    { sendParamsWindow_chan[36] = new Fl_Light_Button(620, 335, 67, 20, "36");
    } // Fl_Light_Button* sendParamsWindow_chan[36]
    { sendParamsWindow_chan[37] = new Fl_Light_Button(620, 355, 67, 20, "37");
    } // Fl_Light_Button* sendParamsWindow_chan[37]
    { sendParamsWindow_chan[38] = new Fl_Light_Button(620, 375, 67, 20, "38");
    } // Fl_Light_Button* sendParamsWindow_chan[38]
    { sendParamsWindow_chan[39] = new Fl_Light_Button(620, 395, 67, 20, "39");
    } // Fl_Light_Button* sendParamsWindow_chan[39]
    { sendParamsWindow_chan[40] = new Fl_Light_Button(620, 415, 67, 20, "40");
    } // Fl_Light_Button* sendParamsWindow_chan[40]
    { sendParamsWindow_chan[41] = new Fl_Light_Button(620, 435, 67, 20, "41");
    } // Fl_Light_Button* sendParamsWindow_chan[41]
    { sendParamsWindow_chan[42] = new Fl_Light_Button(685, 35, 67, 20, "42");
    } // Fl_Light_Button* sendParamsWindow_chan[42]
    { sendParamsWindow_chan[43] = new Fl_Light_Button(685, 55, 67, 20, "43");
    } // Fl_Light_Button* sendParamsWindow_chan[43]
    { sendParamsWindow_chan[44] = new Fl_Light_Button(685, 75, 67, 20, "44");
    } // Fl_Light_Button* sendParamsWindow_chan[44]
    { sendParamsWindow_chan[45] = new Fl_Light_Button(685, 95, 67, 20, "45");
    } // Fl_Light_Button* sendParamsWindow_chan[45]
    { sendParamsWindow_chan[46] = new Fl_Light_Button(685, 115, 67, 20, "46");
    } // Fl_Light_Button* sendParamsWindow_chan[46]
    { sendParamsWindow_chan[47] = new Fl_Light_Button(685, 135, 67, 20, "47");
    } // Fl_Light_Button* sendParamsWindow_chan[47]
    { sendParamsWindow_chan[48] = new Fl_Light_Button(685, 155, 67, 20, "48");
    } // Fl_Light_Button* sendParamsWindow_chan[48]
    { sendParamsWindow_chan[49] = new Fl_Light_Button(685, 175, 67, 20, "49");
    } // Fl_Light_Button* sendParamsWindow_chan[49]
    { sendParamsWindow_chan[50] = new Fl_Light_Button(685, 195, 67, 20, "50");
    } // Fl_Light_Button* sendParamsWindow_chan[50]
    { sendParamsWindow_chan[51] = new Fl_Light_Button(685, 215, 67, 20, "51");
    } // Fl_Light_Button* sendParamsWindow_chan[51]
    { sendParamsWindow_chan[52] = new Fl_Light_Button(685, 235, 67, 20, "52");
    } // Fl_Light_Button* sendParamsWindow_chan[52]
    { sendParamsWindow_chan[53] = new Fl_Light_Button(685, 255, 67, 20, "53");
    } // Fl_Light_Button* sendParamsWindow_chan[53]
    { sendParamsWindow_chan[54] = new Fl_Light_Button(685, 275, 67, 20, "54");
    } // Fl_Light_Button* sendParamsWindow_chan[54]
    { sendParamsWindow_chan[55] = new Fl_Light_Button(685, 295, 67, 20, "55");
    } // Fl_Light_Button* sendParamsWindow_chan[55]
    { sendParamsWindow_chan[56] = new Fl_Light_Button(685, 315, 67, 20, "56");
    } // Fl_Light_Button* sendParamsWindow_chan[56]
    { sendParamsWindow_chan[57] = new Fl_Light_Button(685, 335, 67, 20, "57");
    } // Fl_Light_Button* sendParamsWindow_chan[57]
    { sendParamsWindow_chan[58] = new Fl_Light_Button(685, 355, 67, 20, "58");
    } // Fl_Light_Button* sendParamsWindow_chan[58]
    { sendParamsWindow_chan[59] = new Fl_Light_Button(685, 375, 67, 20, "59");
    } // Fl_Light_Button* sendParamsWindow_chan[59]
    { sendParamsWindow_chan[60] = new Fl_Light_Button(685, 395, 67, 20, "60");
    } // Fl_Light_Button* sendParamsWindow_chan[60]
    { sendParamsWindow_chan[61] = new Fl_Light_Button(685, 415, 67, 20, "61");
    } // Fl_Light_Button* sendParamsWindow_chan[61]
    { sendParamsWindow_chan[62] = new Fl_Light_Button(685, 435, 67, 20, "62");
    } // Fl_Light_Button* sendParamsWindow_chan[62]
    { sendParamsWindow_chan[63] = new Fl_Light_Button(685, 455, 67, 20, "63");
    } // Fl_Light_Button* sendParamsWindow_chan[63]
    { sendParamsWindow_asic = new Fl_Value_Input(460, 386, 15, 24, "ASIC");
      sendParamsWindow_asic->maximum(3);
      sendParamsWindow_asic->step(1);
      sendParamsWindow_asic->callback((Fl_Callback*)cb_sendParamsWindow_asic);
    } // Fl_Value_Input* sendParamsWindow_asic
    { Fl_Button* o = new Fl_Button(555, 455, 63, 20, "set all");
      o->callback((Fl_Callback*)cb_set);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(619, 455, 63, 20, "clear all");
      o->callback((Fl_Callback*)cb_clear);
    } // Fl_Button* o
    { Fl_Text_Display* o = new Fl_Text_Display(705, 5, 15, 20, "Channel disable");
      o->align(Fl_Align(FL_ALIGN_LEFT));
    } // Fl_Text_Display* o
    { sendParamsWindow_test[0] = new Fl_Light_Button(790, 36, 67, 20, "0");
    } // Fl_Light_Button* sendParamsWindow_test[0]
    { sendParamsWindow_test[1] = new Fl_Light_Button(790, 56, 67, 20, "1");
    } // Fl_Light_Button* sendParamsWindow_test[1]
    { sendParamsWindow_test[2] = new Fl_Light_Button(790, 76, 67, 20, "2");
    } // Fl_Light_Button* sendParamsWindow_test[2]
    { sendParamsWindow_test[3] = new Fl_Light_Button(790, 96, 67, 20, "3");
    } // Fl_Light_Button* sendParamsWindow_test[3]
    { sendParamsWindow_test[4] = new Fl_Light_Button(790, 116, 67, 20, "4");
    } // Fl_Light_Button* sendParamsWindow_test[4]
    { sendParamsWindow_test[5] = new Fl_Light_Button(790, 136, 67, 20, "5");
    } // Fl_Light_Button* sendParamsWindow_test[5]
    { sendParamsWindow_test[6] = new Fl_Light_Button(790, 156, 67, 20, "6");
    } // Fl_Light_Button* sendParamsWindow_test[6]
    { sendParamsWindow_test[7] = new Fl_Light_Button(790, 176, 67, 20, "7");
    } // Fl_Light_Button* sendParamsWindow_test[7]
    { sendParamsWindow_test[8] = new Fl_Light_Button(790, 196, 67, 20, "8");
    } // Fl_Light_Button* sendParamsWindow_test[8]
    { sendParamsWindow_test[9] = new Fl_Light_Button(790, 216, 67, 20, "9");
    } // Fl_Light_Button* sendParamsWindow_test[9]
    { sendParamsWindow_test[10] = new Fl_Light_Button(790, 236, 67, 20, "10");
    } // Fl_Light_Button* sendParamsWindow_test[10]
    { sendParamsWindow_test[11] = new Fl_Light_Button(790, 256, 67, 20, "11");
    } // Fl_Light_Button* sendParamsWindow_test[11]
    { sendParamsWindow_test[12] = new Fl_Light_Button(790, 276, 67, 20, "12");
    } // Fl_Light_Button* sendParamsWindow_test[12]
    { sendParamsWindow_test[13] = new Fl_Light_Button(790, 296, 67, 20, "13");
    } // Fl_Light_Button* sendParamsWindow_test[13]
    { sendParamsWindow_test[14] = new Fl_Light_Button(790, 316, 67, 20, "14");
    } // Fl_Light_Button* sendParamsWindow_test[14]
    { sendParamsWindow_test[15] = new Fl_Light_Button(790, 336, 67, 20, "15");
    } // Fl_Light_Button* sendParamsWindow_test[15]
    { sendParamsWindow_test[16] = new Fl_Light_Button(790, 356, 67, 20, "16");
    } // Fl_Light_Button* sendParamsWindow_test[16]
    { sendParamsWindow_test[17] = new Fl_Light_Button(790, 376, 67, 20, "17");
    } // Fl_Light_Button* sendParamsWindow_test[17]
    { sendParamsWindow_test[18] = new Fl_Light_Button(790, 396, 67, 20, "18");
    } // Fl_Light_Button* sendParamsWindow_test[18]
    { sendParamsWindow_test[19] = new Fl_Light_Button(790, 416, 67, 20, "19");
    } // Fl_Light_Button* sendParamsWindow_test[19]
    { sendParamsWindow_test[20] = new Fl_Light_Button(790, 436, 67, 20, "20");
    } // Fl_Light_Button* sendParamsWindow_test[20]
    { sendParamsWindow_test[21] = new Fl_Light_Button(855, 36, 67, 20, "21");
    } // Fl_Light_Button* sendParamsWindow_test[21]
    { sendParamsWindow_test[22] = new Fl_Light_Button(855, 56, 67, 20, "22");
    } // Fl_Light_Button* sendParamsWindow_test[22]
    { sendParamsWindow_test[23] = new Fl_Light_Button(855, 76, 67, 20, "23");
    } // Fl_Light_Button* sendParamsWindow_test[23]
    { sendParamsWindow_test[24] = new Fl_Light_Button(855, 96, 67, 20, "24");
    } // Fl_Light_Button* sendParamsWindow_test[24]
    { sendParamsWindow_test[25] = new Fl_Light_Button(855, 116, 67, 20, "25");
    } // Fl_Light_Button* sendParamsWindow_test[25]
    { sendParamsWindow_test[26] = new Fl_Light_Button(855, 136, 67, 20, "26");
    } // Fl_Light_Button* sendParamsWindow_test[26]
    { sendParamsWindow_test[27] = new Fl_Light_Button(855, 156, 67, 20, "27");
    } // Fl_Light_Button* sendParamsWindow_test[27]
    { sendParamsWindow_test[28] = new Fl_Light_Button(855, 176, 67, 20, "28");
    } // Fl_Light_Button* sendParamsWindow_test[28]
    { sendParamsWindow_test[29] = new Fl_Light_Button(855, 196, 67, 20, "29");
    } // Fl_Light_Button* sendParamsWindow_test[29]
    { sendParamsWindow_test[30] = new Fl_Light_Button(855, 216, 67, 20, "30");
    } // Fl_Light_Button* sendParamsWindow_test[30]
    { sendParamsWindow_test[31] = new Fl_Light_Button(855, 236, 67, 20, "31");
    } // Fl_Light_Button* sendParamsWindow_test[31]
    { sendParamsWindow_test[32] = new Fl_Light_Button(855, 256, 67, 20, "32");
    } // Fl_Light_Button* sendParamsWindow_test[32]
    { sendParamsWindow_test[33] = new Fl_Light_Button(855, 276, 67, 20, "33");
    } // Fl_Light_Button* sendParamsWindow_test[33]
    { sendParamsWindow_test[34] = new Fl_Light_Button(855, 296, 67, 20, "34");
    } // Fl_Light_Button* sendParamsWindow_test[34]
    { sendParamsWindow_test[35] = new Fl_Light_Button(855, 316, 67, 20, "35");
    } // Fl_Light_Button* sendParamsWindow_test[35]
    { sendParamsWindow_test[36] = new Fl_Light_Button(855, 336, 67, 20, "36");
    } // Fl_Light_Button* sendParamsWindow_test[36]
    { sendParamsWindow_test[37] = new Fl_Light_Button(855, 356, 67, 20, "37");
    } // Fl_Light_Button* sendParamsWindow_test[37]
    { sendParamsWindow_test[38] = new Fl_Light_Button(855, 376, 67, 20, "38");
    } // Fl_Light_Button* sendParamsWindow_test[38]
    { sendParamsWindow_test[39] = new Fl_Light_Button(855, 396, 67, 20, "39");
    } // Fl_Light_Button* sendParamsWindow_test[39]
    { sendParamsWindow_test[40] = new Fl_Light_Button(855, 416, 67, 20, "40");
    } // Fl_Light_Button* sendParamsWindow_test[40]
    { sendParamsWindow_test[41] = new Fl_Light_Button(855, 436, 67, 20, "41");
    } // Fl_Light_Button* sendParamsWindow_test[41]
    { sendParamsWindow_test[42] = new Fl_Light_Button(920, 36, 67, 20, "42");
    } // Fl_Light_Button* sendParamsWindow_test[42]
    { sendParamsWindow_test[43] = new Fl_Light_Button(920, 56, 67, 20, "43");
    } // Fl_Light_Button* sendParamsWindow_test[43]
    { sendParamsWindow_test[44] = new Fl_Light_Button(920, 76, 67, 20, "44");
    } // Fl_Light_Button* sendParamsWindow_test[44]
    { sendParamsWindow_test[45] = new Fl_Light_Button(920, 96, 67, 20, "45");
    } // Fl_Light_Button* sendParamsWindow_test[45]
    { sendParamsWindow_test[46] = new Fl_Light_Button(920, 116, 67, 20, "46");
    } // Fl_Light_Button* sendParamsWindow_test[46]
    { sendParamsWindow_test[47] = new Fl_Light_Button(920, 136, 67, 20, "47");
    } // Fl_Light_Button* sendParamsWindow_test[47]
    { sendParamsWindow_test[48] = new Fl_Light_Button(920, 156, 67, 20, "48");
    } // Fl_Light_Button* sendParamsWindow_test[48]
    { sendParamsWindow_test[49] = new Fl_Light_Button(920, 176, 67, 20, "49");
    } // Fl_Light_Button* sendParamsWindow_test[49]
    { sendParamsWindow_test[50] = new Fl_Light_Button(920, 196, 67, 20, "50");
    } // Fl_Light_Button* sendParamsWindow_test[50]
    { sendParamsWindow_test[51] = new Fl_Light_Button(920, 216, 67, 20, "51");
    } // Fl_Light_Button* sendParamsWindow_test[51]
    { sendParamsWindow_test[52] = new Fl_Light_Button(920, 236, 67, 20, "52");
    } // Fl_Light_Button* sendParamsWindow_test[52]
    { sendParamsWindow_test[53] = new Fl_Light_Button(920, 256, 67, 20, "53");
    } // Fl_Light_Button* sendParamsWindow_test[53]
    { sendParamsWindow_test[54] = new Fl_Light_Button(920, 276, 67, 20, "54");
    } // Fl_Light_Button* sendParamsWindow_test[54]
    { sendParamsWindow_test[55] = new Fl_Light_Button(920, 296, 67, 20, "55");
    } // Fl_Light_Button* sendParamsWindow_test[55]
    { sendParamsWindow_test[56] = new Fl_Light_Button(920, 316, 67, 20, "56");
    } // Fl_Light_Button* sendParamsWindow_test[56]
    { sendParamsWindow_test[57] = new Fl_Light_Button(920, 336, 67, 20, "57");
    } // Fl_Light_Button* sendParamsWindow_test[57]
    { sendParamsWindow_test[58] = new Fl_Light_Button(920, 356, 67, 20, "58");
    } // Fl_Light_Button* sendParamsWindow_test[58]
    { sendParamsWindow_test[59] = new Fl_Light_Button(920, 376, 67, 20, "59");
    } // Fl_Light_Button* sendParamsWindow_test[59]
    { sendParamsWindow_test[60] = new Fl_Light_Button(920, 396, 67, 20, "60");
    } // Fl_Light_Button* sendParamsWindow_test[60]
    { sendParamsWindow_test[61] = new Fl_Light_Button(920, 416, 67, 20, "61");
    } // Fl_Light_Button* sendParamsWindow_test[61]
    { sendParamsWindow_test[62] = new Fl_Light_Button(920, 436, 67, 20, "62");
    } // Fl_Light_Button* sendParamsWindow_test[62]
    { sendParamsWindow_test[63] = new Fl_Light_Button(920, 456, 67, 20, "63");
    } // Fl_Light_Button* sendParamsWindow_test[63]
    { Fl_Button* o = new Fl_Button(790, 456, 63, 20, "set all");
      o->callback((Fl_Callback*)cb_set1);
    } // Fl_Button* o
    { Fl_Button* o = new Fl_Button(854, 456, 63, 20, "clear all");
      o->callback((Fl_Callback*)cb_clear1);
    } // Fl_Button* o
    { Fl_Text_Display* o = new Fl_Text_Display(940, 6, 15, 20, "Test enable");
      o->align(Fl_Align(FL_ALIGN_LEFT));
    } // Fl_Text_Display* o
    sendParamsWindow->end();
  } // Fl_Double_Window* sendParamsWindow
  { setHoldTimeWindow = new Fl_Double_Window(312, 165, "Set hold time and take data");
    setHoldTimeWindow->user_data((void*)(this));
    { setHoldTimeWindow_holdTime = new Fl_Value_Input(235, 15, 25, 25, "Hold time setting (all ASICs)::");
    } // Fl_Value_Input* setHoldTimeWindow_holdTime
    { setHoldTimeWindow_setBut = new Fl_Button(70, 65, 80, 25, "Set");
      setHoldTimeWindow_setBut->callback((Fl_Callback*)cb_setHoldTimeWindow_setBut);
    } // Fl_Button* setHoldTimeWindow_setBut
    { setHoldTimeWindow_autorunBut = new Fl_Button(175, 65, 80, 25, "Autorun");
      setHoldTimeWindow_autorunBut->callback((Fl_Callback*)cb_setHoldTimeWindow_autorunBut);
    } // Fl_Button* setHoldTimeWindow_autorunBut
    { Fl_Button* o = new Fl_Button(125, 115, 80, 25, "Close");
      o->callback((Fl_Callback*)cb_Close1);
      o->deactivate();
    } // Fl_Button* o
    setHoldTimeWindow->end();
  } // Fl_Double_Window* setHoldTimeWindow
  { setTrigWindow = new Fl_Double_Window(357, 203, "Trigger Options");
    setTrigWindow->user_data((void*)(this));
    { setTrigWindow_delayTime = new Fl_Value_Input(210, 16, 25, 24, "Trigger delay (units of 3.2 us)");
      setTrigWindow_delayTime->value(3);
    } // Fl_Value_Input* setTrigWindow_delayTime
    { setTrigWindow_timeoutTime = new Fl_Value_Input(211, 106, 25, 24, "Trigger timeout (units of 3.2 us)");
      setTrigWindow_timeoutTime->value(31);
      setTrigWindow_timeoutTime->deactivate();
    } // Fl_Value_Input* setTrigWindow_timeoutTime
    { Fl_Button* o = new Fl_Button(125, 155, 80, 25, "Close");
      o->callback((Fl_Callback*)cb_Close2);
      o->deactivate();
    } // Fl_Button* o
    { setTrigWindow_setDelay = new Fl_Button(255, 15, 80, 25, "Set");
      setTrigWindow_setDelay->callback((Fl_Callback*)cb_setTrigWindow_setDelay);
    } // Fl_Button* setTrigWindow_setDelay
    { setTrigWindow_setTimeout = new Fl_Button(255, 105, 80, 25, "Set");
      setTrigWindow_setTimeout->callback((Fl_Callback*)cb_setTrigWindow_setTimeout);
      setTrigWindow_setTimeout->deactivate();
    } // Fl_Button* setTrigWindow_setTimeout
    { setTrigWindow_useTimeout = new Fl_Value_Input(211, 63, 25, 21, "Use timeout");
      setTrigWindow_useTimeout->value(1);
      setTrigWindow_useTimeout->callback((Fl_Callback*)cb_setTrigWindow_useTimeout);
    } // Fl_Value_Input* setTrigWindow_useTimeout
    { setTrigWindow_setTrigMode = new Fl_Button(255, 60, 80, 25, "Set");
      setTrigWindow_setTrigMode->callback((Fl_Callback*)cb_setTrigWindow_setTrigMode);
    } // Fl_Button* setTrigWindow_setTrigMode
    setTrigWindow->end();
  } // Fl_Double_Window* setTrigWindow
}

void Gui::show() {
  mainWindow->show();
  mainHistogramWindow->show();
  mainImageWindow->show();
  mainLightcurveWindow->show();
  subImageWindow->show();
}
